<option> Français </option>
<option> - - - - - -</option>
<option> Afghan </option>
<option> Albanais </option>
<option> Algérien </option>
<option> Allemand </option>
<option> Américain </option>
<option> Angolais </option>
<option> Argentin </option>
<option> Arménien </option>
<option> Australien </option>
<option> Autrichien </option>
<option> Bangladais </option>
<option> Belge </option>
<option> Béninois </option>
<option> Bosniaque </option>
<option> Botswanais </option>
<option> Bhoutan </option>
<option> Brésilien </option>
<option> Britannique </option>
<option> Bulgare </option>
<option> Burkinabè </option>
<option> Cambodgien </option>
<option> Camerounais </option>
<option> Canadien </option>
<option> Chilien </option>
<option> Chinois </option>
<option> Colombien </option>
<option> Congolais </option>
<option> Cubain </option>
<option> Danois </option>
<option> Ecossais </option>
<option> Egyptien </option>
<option> Espagnol </option>
<option> Estonien </option>
<option> Européen </option>
<option> Finlandais </option>
<option> Gabonais </option>
<option> Georgien </option>
<option> Grec </option>
<option> Guinéen </option>
<option> Haïtien </option>
<option> Hollandais </option>
<option> Hong-Kong </option>
<option> Hongrois </option>
<option> Indien </option>
<option> Indonésien </option>
<option> Irakien </option>
<option> Iranien </option>
<option> Irlandais </option>
<option> Islandais </option>
<option> Israélien </option>
<option> Italien </option>
<option> Ivoirien </option>
<option> Jamaïcain </option>
<option> Japonais </option>
<option> Kazakh </option>
<option> Kirghiz </option>
<option> Kurde </option>
<option> Letton </option>
<option> Libanais </option>
<option> Liechtenstein </option>
<option> Lituanien </option>
<option> Luxembourgeois </option>
<option> Macédonien </option>
<option> Madagascar </option>
<option> Malaisien </option>
<option> Malien </option>
<option> Maltais </option>
<option> Marocain </option>
<option> Mauritanien </option>
<option> Mauricien </option>
<option> Mexicain </option>
<option> Monégasque </option>
<option> Mongol </option>
<option> Néo-Zélandais </option>
<option> Nigérien </option>
<option> Nord Coréen </option>
<option> Norvégien </option>
<option> Pakistanais </option>
<option> Palestinien </option>
<option> Péruvien </option>
<option> Philippins </option>
<option> Polonais </option>
<option> Portoricain </option>
<option> Portugais </option>
<option> Roumain </option>
<option> Russe </option>
<option> Sénégalais </option>
<option> Serbe </option>
<option> Serbo-croate </option>
<option> Singapour </option>
<option> Slovaque </option>
<option> Soviétique </option>
<option> Sri-lankais </option>
<option> Sud-Africain </option>
<option> Sud-Coréen </option>
<option> Suédois </option>
<option> Suisse </option>
<option> Syrien </option>
<option> Tadjik </option>
<option> Taïwanais </option>
<option> Tchadien </option>
<option> Tchèque </option>
<option> Thaïlandais </option>
<option> Tunisien </option>
<option> Turc </option>
<option> Ukrainien </option>
<option> Uruguayen </option>
<option> Vénézuélien </option>
<option> Vietnamien </option>